package com.itson.sistema.integral.de.tramites.vehiculares.ui;

import com.itson.sistema.integral.de.tramites.vehiculares.ui.componentes.EncabezadoComponente;
import com.itson.sistema.integral.de.tramites.vehiculares.ui.formularios.FormularioPlacas;
import com.itson.sistema.integral.de.tramites.vehiculares.ui.tablas.TablaLicenciasPanel;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;

public class AdministradorPlacas extends javax.swing.JFrame {

    public AdministradorPlacas() {
        initComponents();

        setLayout(new BorderLayout());

        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        JPanel contenido = new JPanel();
        contenido.setLayout(new BorderLayout(10, 10));

        FormularioPlacas formulario = new FormularioPlacas();

        TablaLicenciasPanel tablaPlacas = new TablaLicenciasPanel();

        formulario.comboTipoTramite.addActionListener(e -> actualizarMonto(formulario));
        formulario.checkAutoNuevo.addActionListener(e -> actualizarMonto(formulario));

        contenido.add(formulario, BorderLayout.NORTH);
        contenido.add(tablaPlacas, BorderLayout.CENTER);

        JPanel controles = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 10));

        JButton btnRegistrar = new JButton("Registrar placa");
        JButton btnCancelar = new JButton("Cancelar trámite");

        controles.add(btnRegistrar);
        controles.add(btnCancelar);

        EncabezadoComponente encabezado = new EncabezadoComponente();

        panel.add(encabezado, BorderLayout.NORTH);
        panel.add(contenido, BorderLayout.CENTER);
        panel.add(controles, BorderLayout.SOUTH);

        add(panel, BorderLayout.CENTER);
    }

    private void actualizarMonto(FormularioPlacas f) {
        boolean esNuevo = f.comboTipoTramite.getSelectedItem().toString().equals("Auto Nuevo")
                || f.checkAutoNuevo.isSelected();

        double monto = esNuevo ? 1500 : 1000;
        f.txtMonto.setText("$" + monto);

        f.txtNumPlacasAnteriores.setEnabled(!esNuevo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
