package com.itson.sistema.integral.de.tramites.vehiculares.ui;

import com.itson.sistema.integral.de.tramites.vehiculares.ui.componentes.EncabezadoComponente;
import com.itson.sistema.integral.de.tramites.vehiculares.ui.formularios.FormularioConsultas;
import com.itson.sistema.integral.de.tramites.vehiculares.ui.tablas.TablaHistorialPanel;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;

public class AdministradorConsultas extends javax.swing.JFrame {

    public AdministradorConsultas() {
        initComponents();

        setLayout(new BorderLayout());

        JPanel panel = new JPanel(new BorderLayout());
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        JPanel contenido = new JPanel(new BorderLayout(10, 10));

        FormularioConsultas formulario = new FormularioConsultas();
        TablaHistorialPanel tablaHistorial = new TablaHistorialPanel();

        formulario.btnBuscar.addActionListener(e -> {
            // Limpiar la tabla antes de agregar resultados
            tablaHistorial.limpiarTabla();

            System.out.println("Buscando historial con criterios:");
            System.out.println("RFC: " + formulario.txtRFC.getText());
            System.out.println("Nombre: " + formulario.txtNombre.getText());
            System.out.println("Año: " + formulario.txtAnioNacimiento.getText());
            System.out.println("Tipo: " + formulario.comboTipoConsulta.getSelectedItem());

            // Agregar datos de ejemplo
            tablaHistorial.agregarFila("2025-01-14", "Licencia", "Juan Pérez", 900);
            tablaHistorial.agregarFila("2025-02-20", "Placas", "María López", 1500);
        });

        contenido.add(formulario, BorderLayout.NORTH);
        contenido.add(tablaHistorial, BorderLayout.CENTER);

        JPanel controles = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 10));
        JButton btnExportar = new JButton("Exportar PDF");
        JButton btnCerrar = new JButton("Cerrar");

        controles.add(btnExportar);
        controles.add(btnCerrar);

        btnCerrar.addActionListener(e -> dispose());

        EncabezadoComponente encabezado = new EncabezadoComponente();

        panel.add(encabezado, BorderLayout.NORTH);
        panel.add(contenido, BorderLayout.CENTER);
        panel.add(controles, BorderLayout.SOUTH);

        add(panel, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
