package com.itson.sistema.integral.de.tramites.vehiculares.ui;

import com.itson.sistema.integral.de.tramites.vehiculares.ui.componente.EncabezadoComponente;
import com.itson.sistema.integral.de.tramites.vehiculares.ui.formulario.FormularioPlacas;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;

public class ModuloPlacas extends javax.swing.JFrame {

    public ModuloPlacas() {
        initComponents();

        setTitle("Administración de Trámites de Placas");
        setLayout(new BorderLayout());

        JPanel panelPrincipal = new JPanel(new BorderLayout());
        panelPrincipal.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        EncabezadoComponente encabezado = new EncabezadoComponente();
        FormularioPlacas formulario = new FormularioPlacas();

        JPanel controles = new JPanel(new FlowLayout(FlowLayout.RIGHT, 10, 10));
        JButton btnRegistrar = new JButton("Registrar Placa");
        JButton btnCancelar = new JButton("Cancelar Trámite");
        controles.add(btnRegistrar);
        controles.add(btnCancelar);

        JPanel contenido = new JPanel(new BorderLayout(10, 10));
        contenido.add(formulario, BorderLayout.NORTH);
        contenido.add(controles, BorderLayout.SOUTH);

        panelPrincipal.add(encabezado, BorderLayout.NORTH);
        panelPrincipal.add(contenido, BorderLayout.CENTER);

        add(panelPrincipal, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
