package com.itson.sistema.integral.de.tramites.vehiculares.ui;

import com.itson.sistema.integral.de.tramites.vehiculares.ui.componentes.EncabezadoComponente;
import com.itson.sistema.integral.de.tramites.vehiculares.ui.formularios.FormularioLicencias;
import java.awt.BorderLayout;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

public class ModuloLicencias extends javax.swing.JFrame {

    public ModuloLicencias() {
        initComponents();

        setLayout(new BorderLayout());

        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        JPanel contenido = new JPanel();
        contenido.setLayout(new BorderLayout(10, 10));

        FormularioLicencias formulario = new FormularioLicencias();
        formulario.comboVigencias.addActionListener(e -> actualizarMonto(formulario));
        formulario.checkDiscapacitado.addActionListener(e -> actualizarMonto(formulario));

        EncabezadoComponente encabezado = new EncabezadoComponente();

        contenido.add(formulario, BorderLayout.NORTH);

        panel.add(encabezado, BorderLayout.NORTH);
        panel.add(contenido, BorderLayout.CENTER);

        add(panel, BorderLayout.CENTER);
    }

    private void actualizarMonto(FormularioLicencias f) {
        double monto = switch (f.comboVigencias.getSelectedItem().toString()) {
            case "1 Year" ->
                500;
            case "2 Year" ->
                900;
            case "3 Year" ->
                1200;
            default ->
                0;
        };

        if (f.checkDiscapacitado.isSelected()) {
            monto *= 0.5;
        }

        f.txtMonto.setText("$" + monto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
